version: '3.7'

services:
  mysql:
    image: mysql
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 'zarco'
      MYSQL_DATABASE: 'coordinadora_prueba'
    ports:
      - "3306:3306"
  nodered:
    image: nodered/node-red
    container_name: nodered-container
    ports:
      - "1880:1880"
    depends_on:
      - mysql